// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrv8nTwvhKOiSlnvZGnY8K14JasBeIv3k',
    appId: '1:567861557154:web:132662741070cbaeae64fb',
    messagingSenderId: '567861557154',
    projectId: 'fooddeliveryapp-7d7be',
    authDomain: 'fooddeliveryapp-7d7be.firebaseapp.com',
    databaseURL: 'https://fooddeliveryapp-7d7be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddeliveryapp-7d7be.appspot.com',
    measurementId: 'G-953DFLTTVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7TOApQQ0ULiiacHW9nZlI-DJw8d4_YwQ',
    appId: '1:567861557154:android:9635ba9210e28d90ae64fb',
    messagingSenderId: '567861557154',
    projectId: 'fooddeliveryapp-7d7be',
    databaseURL: 'https://fooddeliveryapp-7d7be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddeliveryapp-7d7be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGQL5pU02O3Gl1nx8gJgNeVYs_QyWEU1I',
    appId: '1:567861557154:ios:a2f205a5d9f70164ae64fb',
    messagingSenderId: '567861557154',
    projectId: 'fooddeliveryapp-7d7be',
    databaseURL: 'https://fooddeliveryapp-7d7be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddeliveryapp-7d7be.appspot.com',
    iosBundleId: 'com.example.nomnom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGQL5pU02O3Gl1nx8gJgNeVYs_QyWEU1I',
    appId: '1:567861557154:ios:557df23c2fd37071ae64fb',
    messagingSenderId: '567861557154',
    projectId: 'fooddeliveryapp-7d7be',
    databaseURL: 'https://fooddeliveryapp-7d7be-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddeliveryapp-7d7be.appspot.com',
    iosBundleId: 'com.example.nomnom.RunnerTests',
  );
}
